/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fadmin.java
 *
 * Created on Apr 17, 2010, 9:03:38 PM
 */

package banhang;
import java.rmi.Naming;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Duc
 */
public class fadmin extends javax.swing.JFrame {
    private Control.RemoteServer Serverconnection1;
    String ip=new hamgoi().docip();
    String[] s2=new String[11];
    /** Creates new form fadmin */
    public fadmin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fadmin = new javax.swing.JFrame();
        pmenuadmin = new javax.swing.JPanel();
        pmenunorth = new javax.swing.JPanel();
        lquyenacc = new javax.swing.JLabel();
        lhi = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lacc = new javax.swing.JLabel();
        pmenucenter = new javax.swing.JPanel();
        pbcenter1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bthaydoiip = new javax.swing.JButton();
        lip = new javax.swing.JLabel();
        bthemacc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bdanhsachacc = new javax.swing.JButton();
        pmenusouth = new javax.swing.JPanel();
        pmenusouth1 = new javax.swing.JPanel();
        bexit = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        pquyenadmin = new javax.swing.JPanel();
        jProgressBar3 = new javax.swing.JProgressBar();
        pcenter = new javax.swing.JPanel();
        pdangky = new java.awt.Panel();
        rb1 = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        tfmanv = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tftennv = new javax.swing.JTextField();
        cbpass = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cbuse = new javax.swing.JLabel();
        bhuy = new javax.swing.JButton();
        bthem = new javax.swing.JButton();
        cbma = new javax.swing.JLabel();
        cbten = new javax.swing.JLabel();
        rb2 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        rb3 = new javax.swing.JRadioButton();
        tfusername = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        rb4 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        cbnhaplai = new javax.swing.JLabel();
        tfnhaplai = new javax.swing.JPasswordField();
        tfpassword = new javax.swing.JPasswordField();
        bgacc = new javax.swing.ButtonGroup();
        pdoiip = new java.awt.Panel();
        tfip = new javax.swing.JTextField();
        bthaydoi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar8 = new javax.swing.JProgressBar();
        jProgressBar10 = new javax.swing.JProgressBar();
        jProgressBar11 = new javax.swing.JProgressBar();
        lcbip = new javax.swing.JLabel();
        jProgressBar9 = new javax.swing.JProgressBar();
        dthongbao = new javax.swing.JDialog(fadmin,true);
        jLabel38 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        plietkeacc = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablelietke = new javax.swing.JTable();
        jLabel42 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        psuadoi = new java.awt.Panel();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tftimkiem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        thongbaothanhcong = new javax.swing.JOptionPane();
        dketnoi = new javax.swing.JDialog(fadmin,true);
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        fadmin.setTitle("Phân vùng admin");
        fadmin.setMinimumSize(new java.awt.Dimension(800, 600));
        fadmin.setResizable(false);

        pmenuadmin.setPreferredSize(new java.awt.Dimension(230, 600));
        pmenuadmin.setRequestFocusEnabled(false);
        pmenuadmin.setLayout(new java.awt.BorderLayout());

        pmenunorth.setPreferredSize(new java.awt.Dimension(200, 180));

        lquyenacc.setForeground(new java.awt.Color(0, 0, 255));
        lquyenacc.setText("Bạn đang đăng nhập với quyền admin");

        lhi.setFont(new java.awt.Font("Times New Roman", 1, 12));
        lhi.setForeground(new java.awt.Color(255, 0, 51));
        lhi.setText("Xin chào");

        l1.setText("Bạn có quyền quản lý");

        l3.setText("1> Địa chỉ Server.");

        l4.setText("2> Toàn bộ account trong hệ thống.");

        jProgressBar1.setBackground(new java.awt.Color(204, 204, 204));

        lacc.setFont(new java.awt.Font("Times New Roman", 1, 14));
        lacc.setForeground(new java.awt.Color(255, 0, 153));
        lacc.setText(new hamgoi().docusername());

        javax.swing.GroupLayout pmenunorthLayout = new javax.swing.GroupLayout(pmenunorth);
        pmenunorth.setLayout(pmenunorthLayout);
        pmenunorthLayout.setHorizontalGroup(
            pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmenunorthLayout.createSequentialGroup()
                .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pmenunorthLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lquyenacc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmenunorthLayout.createSequentialGroup()
                                .addComponent(lhi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lacc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(pmenunorthLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(l1)
                                .addGap(83, 83, 83))))
                    .addGroup(pmenunorthLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l4)
                            .addComponent(l3))))
                .addContainerGap())
        );
        pmenunorthLayout.setVerticalGroup(
            pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmenunorthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lhi)
                    .addComponent(lacc, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lquyenacc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pmenuadmin.add(pmenunorth, java.awt.BorderLayout.NORTH);

        pmenucenter.setPreferredSize(new java.awt.Dimension(200, 400));
        pmenucenter.setLayout(new java.awt.BorderLayout());

        pbcenter1.setPreferredSize(new java.awt.Dimension(200, 250));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Đia chỉ Server hiện tại là");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("IP:");

        bthaydoiip.setText("Thay đổi");
        bthaydoiip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthaydoiipActionPerformed(evt);
            }
        });

        lip.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lip.setForeground(new java.awt.Color(255, 0, 0));
        lip.setText(new hamgoi().docip());

        bthemacc.setText("Thêm");
        bthemacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthemaccActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Đăng ký thêm account");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Quản lý phân quyền account hiên tại");

        bdanhsachacc.setText("Quản lý account");
        bdanhsachacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdanhsachaccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pbcenter1Layout = new javax.swing.GroupLayout(pbcenter1);
        pbcenter1.setLayout(pbcenter1Layout);
        pbcenter1Layout.setHorizontalGroup(
            pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbcenter1Layout.createSequentialGroup()
                .addGroup(pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pbcenter1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGroup(pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pbcenter1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(pbcenter1Layout.createSequentialGroup()
                                                .addComponent(lip, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bthaydoiip))
                                            .addComponent(jLabel4)))
                                    .addGroup(pbcenter1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(bthemacc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(44, 44, 44))
                            .addComponent(jLabel3)))
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(bdanhsachacc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pbcenter1Layout.setVerticalGroup(
            pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbcenter1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lip, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bthaydoiip)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bthemacc)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bdanhsachacc)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pmenucenter.add(pbcenter1, java.awt.BorderLayout.NORTH);

        pmenuadmin.add(pmenucenter, java.awt.BorderLayout.CENTER);

        pmenusouth.setLayout(new java.awt.BorderLayout());

        pmenusouth1.setPreferredSize(new java.awt.Dimension(200, 100));

        bexit.setText("Exit");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        jProgressBar2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pmenusouth1Layout = new javax.swing.GroupLayout(pmenusouth1);
        pmenusouth1.setLayout(pmenusouth1Layout);
        pmenusouth1Layout.setHorizontalGroup(
            pmenusouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmenusouth1Layout.createSequentialGroup()
                .addGroup(pmenusouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pmenusouth1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pmenusouth1Layout.setVerticalGroup(
            pmenusouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmenusouth1Layout.createSequentialGroup()
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bexit)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pmenusouth.add(pmenusouth1, java.awt.BorderLayout.SOUTH);

        pmenuadmin.add(pmenusouth, java.awt.BorderLayout.PAGE_END);

        fadmin.getContentPane().add(pmenuadmin, java.awt.BorderLayout.WEST);

        pquyenadmin.setPreferredSize(new java.awt.Dimension(600, 600));

        jProgressBar3.setBackground(new java.awt.Color(204, 204, 204));

        pcenter.setMinimumSize(new java.awt.Dimension(454, 811));
        pcenter.setPreferredSize(new java.awt.Dimension(555, 600));
        pcenter.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pquyenadminLayout = new javax.swing.GroupLayout(pquyenadmin);
        pquyenadmin.setLayout(pquyenadminLayout);
        pquyenadminLayout.setHorizontalGroup(
            pquyenadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pquyenadminLayout.createSequentialGroup()
                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pcenter, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
        );
        pquyenadminLayout.setVerticalGroup(
            pquyenadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(pcenter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );

        fadmin.getContentPane().add(pquyenadmin, java.awt.BorderLayout.CENTER);

        bgacc.add(rb1);
        rb1.setSelected(true);
        rb1.setText("Admin");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel35.setForeground(new java.awt.Color(0, 0, 255));
        jLabel35.setText("Phân quyền account: ");

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel34.setForeground(new java.awt.Color(0, 0, 255));
        jLabel34.setText("Mã nhân viên");

        cbpass.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbpass.setForeground(new java.awt.Color(255, 0, 0));
        cbpass.setText(" ");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel32.setForeground(new java.awt.Color(0, 0, 255));
        jLabel32.setText("Họ tên nhân viên");

        cbuse.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbuse.setForeground(new java.awt.Color(255, 0, 0));
        cbuse.setText(" ");

        bhuy.setText("Hủy");
        bhuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhuyActionPerformed(evt);
            }
        });

        bthem.setText("Thêm");
        bthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthemActionPerformed(evt);
            }
        });

        cbma.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbma.setForeground(new java.awt.Color(255, 0, 0));
        cbma.setText(" ");

        cbten.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbten.setForeground(new java.awt.Color(255, 0, 0));
        cbten.setText(" ");

        bgacc.add(rb2);
        rb2.setText("Quản lý bán hàng");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("Đăng ký acc");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel29.setForeground(new java.awt.Color(0, 0, 255));
        jLabel29.setText("Username");

        bgacc.add(rb3);
        rb3.setText("Quản lý kho");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel30.setForeground(new java.awt.Color(0, 0, 255));
        jLabel30.setText("Password");

        bgacc.add(rb4);
        rb4.setText("Giao hàng");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Nhập lại password");

        cbnhaplai.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbnhaplai.setForeground(new java.awt.Color(255, 0, 0));
        cbnhaplai.setText(" ");

        javax.swing.GroupLayout pdangkyLayout = new javax.swing.GroupLayout(pdangky);
        pdangky.setLayout(pdangkyLayout);
        pdangkyLayout.setHorizontalGroup(
            pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdangkyLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pdangkyLayout.createSequentialGroup()
                        .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pdangkyLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel34))
                            .addGroup(pdangkyLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(bthem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bhuy, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pdangkyLayout.createSequentialGroup()
                                .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pdangkyLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel35)
                                            .addComponent(rb1))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb4)))
                        .addContainerGap())
                    .addGroup(pdangkyLayout.createSequentialGroup()
                        .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pdangkyLayout.createSequentialGroup()
                                .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addGroup(pdangkyLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)))
                                .addGap(42, 42, 42)
                                .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(cbpass, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(tfusername, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(cbuse, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(cbnhaplai, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(tfnhaplai, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(tftennv, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(cbma, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(cbten, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(tfmanv, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pdangkyLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel28)
                                .addGap(125, 125, 125)))
                        .addGap(80, 80, 80))))
        );
        pdangkyLayout.setVerticalGroup(
            pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdangkyLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel28)
                .addGap(34, 34, 34)
                .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addGroup(pdangkyLayout.createSequentialGroup()
                        .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbuse)
                        .addGap(12, 12, 12)
                        .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(tfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(cbpass)))
                .addGap(11, 11, 11)
                .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnhaplai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbnhaplai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tftennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbten)
                .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pdangkyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pdangkyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(cbma)
                .addGap(11, 11, 11)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb3)
                    .addComponent(rb2)
                    .addComponent(rb4)
                    .addComponent(rb1))
                .addGap(36, 36, 36)
                .addGroup(pdangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bhuy)
                    .addComponent(bthem))
                .addGap(32, 32, 32))
        );

        tfip.setFont(new java.awt.Font("Times New Roman", 1, 18));
        tfip.setForeground(new java.awt.Color(255, 0, 51));

        bthaydoi.setText("Thay đổi");
        bthaydoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthaydoiActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Địa chỉ Server mới");

        jButton2.setText("Hủy bỏ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText(new hamgoi().docip());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Địa chỉ Server hiện tại là");

        lcbip.setFont(new java.awt.Font("Times New Roman", 2, 12));
        lcbip.setForeground(new java.awt.Color(255, 0, 0));
        lcbip.setText(" ");

        javax.swing.GroupLayout pdoiipLayout = new javax.swing.GroupLayout(pdoiip);
        pdoiip.setLayout(pdoiipLayout);
        pdoiipLayout.setHorizontalGroup(
            pdoiipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdoiipLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(pdoiipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pdoiipLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jProgressBar8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jProgressBar9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pdoiipLayout.createSequentialGroup()
                        .addComponent(jProgressBar11, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pdoiipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pdoiipLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pdoiipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pdoiipLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGroup(pdoiipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pdoiipLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pdoiipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lcbip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(tfip, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(pdoiipLayout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jLabel6))))
                                    .addComponent(jLabel7))
                                .addGap(15, 15, 15))
                            .addGroup(pdoiipLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(bthaydoi)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jProgressBar10, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        pdoiipLayout.setVerticalGroup(
            pdoiipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdoiipLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pdoiipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pdoiipLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jProgressBar11, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pdoiipLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar10, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                    .addGroup(pdoiipLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pdoiipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(pdoiipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pdoiipLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7))
                            .addGroup(pdoiipLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lcbip)
                        .addGap(18, 18, 18)
                        .addGroup(pdoiipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bthaydoi)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );

        dthongbao.setTitle("Thay đổi thành công");

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel38.setForeground(new java.awt.Color(0, 0, 204));
        jLabel38.setText("Địa chỉ mới sẽ được áp dụng cho lần đăng nhập sau.");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dthongbaoLayout = new javax.swing.GroupLayout(dthongbao.getContentPane());
        dthongbao.getContentPane().setLayout(dthongbaoLayout);
        dthongbaoLayout.setHorizontalGroup(
            dthongbaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dthongbaoLayout.createSequentialGroup()
                .addGroup(dthongbaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dthongbaoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel38))
                    .addGroup(dthongbaoLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dthongbaoLayout.setVerticalGroup(
            dthongbaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dthongbaoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablelietke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Quyền hạn", "Họ tên nhân viên sử dụng", "Mã nhân viên"
            }
        ));
        jScrollPane2.setViewportView(tablelietke);
        tablelietke.getColumnModel().getColumn(3).setResizable(false);

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel42.setForeground(new java.awt.Color(255, 0, 0));
        jLabel42.setText("Danh sách account đã đăng ký.");

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plietkeaccLayout = new javax.swing.GroupLayout(plietkeacc);
        plietkeacc.setLayout(plietkeaccLayout);
        plietkeaccLayout.setHorizontalGroup(
            plietkeaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plietkeaccLayout.createSequentialGroup()
                .addGroup(plietkeaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plietkeaccLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel42))
                    .addGroup(plietkeaccLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plietkeaccLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plietkeaccLayout.setVerticalGroup(
            plietkeaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plietkeaccLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jButton6.setText("Xóa account");

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Tên nhân viên", "Mã nhân viên", "Quyền hạn", "ID account"
            }
        ));
        jScrollPane3.setViewportView(tb1);
        tb1.getColumnModel().getColumn(3).setResizable(false);

        jButton5.setText("Sửa đổi");

        jButton4.setText("Tìm kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Theo username hoặc mã nhân viên");

        javax.swing.GroupLayout psuadoiLayout = new javax.swing.GroupLayout(psuadoi);
        psuadoi.setLayout(psuadoiLayout);
        psuadoiLayout.setHorizontalGroup(
            psuadoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psuadoiLayout.createSequentialGroup()
                .addGroup(psuadoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(psuadoiLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(psuadoiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(psuadoiLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(psuadoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(psuadoiLayout.createSequentialGroup()
                                .addComponent(tftimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)))))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        psuadoiLayout.setVerticalGroup(
            psuadoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psuadoiLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(psuadoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(psuadoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        dketnoi.setTitle("Lỗi kết nối");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Không thể kết nối tới Server");

        jButton8.setText("OK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dketnoiLayout = new javax.swing.GroupLayout(dketnoi.getContentPane());
        dketnoi.getContentPane().setLayout(dketnoiLayout);
        dketnoiLayout.setHorizontalGroup(
            dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dketnoiLayout.createSequentialGroup()
                .addGroup(dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dketnoiLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9))
                    .addGroup(dketnoiLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        dketnoiLayout.setVerticalGroup(
            dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dketnoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bthemaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthemaccActionPerformed
        tfusername.setText("");
        tfpassword.setText("");
        tfnhaplai.setText("");
        tftennv.setText("");
        tfmanv.setText("");
        pcenter.removeAll();
        fadmin.pack();
        pcenter.add(pdangky,java.awt.BorderLayout.CENTER);
        fadmin.pack();
}//GEN-LAST:event_bthemaccActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        System.exit(1);
}//GEN-LAST:event_bexitActionPerformed

    private void bhuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhuyActionPerformed
        pcenter.removeAll();
        fadmin.pack();
}//GEN-LAST:event_bhuyActionPerformed

    private void bthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthemActionPerformed
        String quyen="";
        boolean check=true;
        cbuse.setText("");
        cbpass.setText("");
        cbnhaplai.setText("");
        cbten.setText("");
        cbma.setText("");
        if(new hamgoi().ktString(tfusername.getText().trim())==false){
            cbuse.setText("* Bat buoc phai nhap thong tin nay!");
            check=false;
        }
        if(new hamgoi().ktString(tfpassword.getText().trim())==false){
            cbpass.setText("* Bat buoc phai nhap thong tin nay!");
            check=false;
        }
        if(new hamgoi().ktString(tfnhaplai.getText().trim())==false){
            cbnhaplai.setText("* Bat buoc phai nhap thong tin nay!");
            check=false;
        }
        if(new hamgoi().ktString(tftennv.getText().trim())==false){
            cbten.setText("* Bat buoc phai nhap thong tin nay!");
            check=false;
        }
        if(new hamgoi().ktString(tfmanv.getText().trim())==false){
            cbma.setText("* Bat buoc phai nhap thong tin nay!");
            check=false;
        }
        if(tfpassword.getText().trim().equals(tfnhaplai.getText().trim())!=true){
            cbnhaplai.setText("* Password nhap lai khac password dang ky!");
            check=false;
        }
        if(check==true){
            try{
                if(rb1.isSelected()==true)
                    quyen="admin";
                if(rb2.isSelected()==true)
                    quyen="banhang";
                if(rb3.isSelected()==true)
                    quyen="khohang";
                if(rb4.isSelected()==true)
                    quyen="giaohang";
                Serverconnection1 = (Control.RemoteServer)Naming.lookup("rmi://"+ip+":1099/Server");
                s2=Serverconnection1.data("taoaccount",tfusername.getText(),tfpassword.getText(),tftennv.getText(),tfmanv.getText(),quyen,"","","","","");
                if(s2[0].equals("trungusername")==true){
                    cbuse.setText("* Username nay da co nguoi su dung!");
                }
                else if(s2[0].equals("thanhcong")==true){
                    javax.swing.JOptionPane.showMessageDialog(thongbaothanhcong, "Tao tai khoang than cong");
                    pcenter.removeAll();
                    fadmin.pack();
                }
                System.out.println(s2[0]);
                
            } catch(Exception e){
                dketnoi.pack();
                dketnoi.setVisible(true);
            }
        }
}//GEN-LAST:event_bthemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       pcenter.removeAll();
       fadmin.pack();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bthaydoiipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthaydoiipActionPerformed
        lcbip.setText("");
        tfip.setText("");
        pcenter.removeAll();
        fadmin.pack();
        pcenter.add(pdoiip, java.awt.BorderLayout.NORTH);
        fadmin.pack();
    }//GEN-LAST:event_bthaydoiipActionPerformed

    private void bthaydoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthaydoiActionPerformed
        if(new hamgoi().ktString(tfip.getText())==false){
            lcbip.setText("*Bạn phải nhập địa chỉ mới!");
        }
        else{
            new hamgoi().ghiip(tfip.getText());
            dthongbao.pack();
            dthongbao.setVisible(true);
        }
    }//GEN-LAST:event_bthaydoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dthongbao.setVisible(false);
        pcenter.removeAll();
        fadmin.pack();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bdanhsachaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdanhsachaccActionPerformed
        pcenter.removeAll();
        fadmin.pack();
        pcenter.add(psuadoi, java.awt.BorderLayout.NORTH);
        fadmin.pack();
    }//GEN-LAST:event_bdanhsachaccActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pcenter.remove(plietkeacc);
        fadmin.pack();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dketnoi.setVisible(false);
}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model=(DefaultTableModel)tb1.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            Serverconnection1 = (Control.RemoteServer)Naming.lookup("rmi://"+ip+":1099/Server");
            s2=Serverconnection1.data("timaccount",tftimkiem.getText(),"","","","","","","","","");
            if(s2[0].equals("timthay")==true){
                model.addRow(new Object[] {s2[1],s2[2],s2[3],s2[4],s2[5],s2[6]});
            }
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               //new Login().abc();

                new fadmin().fadmin.pack();
                new fadmin().fadmin.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdanhsachacc;
    private javax.swing.JButton bexit;
    private javax.swing.ButtonGroup bgacc;
    private javax.swing.JButton bhuy;
    private javax.swing.JButton bthaydoi;
    private javax.swing.JButton bthaydoiip;
    private javax.swing.JButton bthem;
    private javax.swing.JButton bthemacc;
    private javax.swing.JLabel cbma;
    private javax.swing.JLabel cbnhaplai;
    private javax.swing.JLabel cbpass;
    private javax.swing.JLabel cbten;
    private javax.swing.JLabel cbuse;
    private javax.swing.JDialog dketnoi;
    private javax.swing.JDialog dthongbao;
    public javax.swing.JFrame fadmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar10;
    private javax.swing.JProgressBar jProgressBar11;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar8;
    private javax.swing.JProgressBar jProgressBar9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel lacc;
    private javax.swing.JLabel lcbip;
    private javax.swing.JLabel lhi;
    private javax.swing.JLabel lip;
    private javax.swing.JLabel lquyenacc;
    private javax.swing.JPanel pbcenter1;
    private javax.swing.JPanel pcenter;
    private java.awt.Panel pdangky;
    private java.awt.Panel pdoiip;
    private java.awt.Panel plietkeacc;
    private javax.swing.JPanel pmenuadmin;
    private javax.swing.JPanel pmenucenter;
    private javax.swing.JPanel pmenunorth;
    private javax.swing.JPanel pmenusouth;
    private javax.swing.JPanel pmenusouth1;
    private javax.swing.JPanel pquyenadmin;
    private java.awt.Panel psuadoi;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JTable tablelietke;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField tfip;
    private javax.swing.JTextField tfmanv;
    private javax.swing.JPasswordField tfnhaplai;
    private javax.swing.JPasswordField tfpassword;
    private javax.swing.JTextField tftennv;
    private javax.swing.JTextField tftimkiem;
    private javax.swing.JTextField tfusername;
    private javax.swing.JOptionPane thongbaothanhcong;
    // End of variables declaration//GEN-END:variables

}
