/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fbanhang.java
 *
 * Created on Apr 20, 2010, 9:24:56 PM
 */

package banhang;
import java.rmi.Naming;
/**
 *
 * @author Duc
 */
public class fbanhang extends javax.swing.JFrame {
    private Control.RemoteServer Serverconnection1;
    String ip=new hamgoi().docip();
    String[] s2=new String[11];
    String hangmua="";
    String hang="";
    long tien=0;
    /** Creates new form fbanhang */
    public fbanhang() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fbanhang = new javax.swing.JFrame();
        pmenu = new javax.swing.JPanel();
        pmenunorth = new javax.swing.JPanel();
        lquyenacc = new javax.swing.JLabel();
        lhi = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lacc = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pmenucenter = new javax.swing.JPanel();
        pbcenter1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bhoadon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bcapnhat = new javax.swing.JButton();
        pmenusouth = new javax.swing.JPanel();
        pmenusouth1 = new javax.swing.JPanel();
        bexit = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        pchinh = new javax.swing.JPanel();
        jProgressBar3 = new javax.swing.JProgressBar();
        pcenter = new javax.swing.JPanel();
        dyeucaugiaohang = new javax.swing.JDialog(fbanhang,true);
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pbanhang = new java.awt.Panel();
        jButton2 = new javax.swing.JButton();
        lcbdiachi = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfkhachhang = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tongtien = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfdiachi = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        tfnv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lcbnv = new javax.swing.JLabel();
        lcbkhachhang = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfsdt = new javax.swing.JTextField();
        lhangmua = new javax.swing.JLabel();
        pdonhang = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        bchuyentiep = new javax.swing.JButton();
        bhuydon = new javax.swing.JButton();
        flietke = new javax.swing.JFrame();
        jLabel31 = new javax.swing.JLabel();
        tfktma = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tfsl = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        dkiemtrama = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        dmasai = new javax.swing.JDialog();
        jLabel34 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        thongbaothanhcong = new javax.swing.JOptionPane();
        dketnoi = new javax.swing.JDialog(fbanhang,true);
        jLabel35 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();

        fbanhang.setTitle("Quản lý kho hàng");
        fbanhang.setMinimumSize(new java.awt.Dimension(800, 600));
        fbanhang.setResizable(false);

        pmenu.setPreferredSize(new java.awt.Dimension(230, 600));
        pmenu.setRequestFocusEnabled(false);
        pmenu.setLayout(new java.awt.BorderLayout());

        pmenunorth.setPreferredSize(new java.awt.Dimension(200, 180));

        lquyenacc.setForeground(new java.awt.Color(0, 0, 255));
        lquyenacc.setText("Bạn đang đăng nhập với quyền bán hàng");

        lhi.setFont(new java.awt.Font("Times New Roman", 1, 12));
        lhi.setForeground(new java.awt.Color(255, 0, 51));
        lhi.setText("Xin chào");

        l1.setText("Bạn có quyền quản lý");

        l3.setText("1> Hóa đơn đặt hàng trược tiếp.");

        l4.setText("2> Đơn đặt hàng online.");

        jProgressBar1.setBackground(new java.awt.Color(204, 204, 204));

        lacc.setFont(new java.awt.Font("Times New Roman", 1, 14));
        lacc.setForeground(new java.awt.Color(255, 0, 153));
        lacc.setText(new hamgoi().docusername());

        jLabel5.setText("3> Phiếu yêu cầu giao hàng.");

        javax.swing.GroupLayout pmenunorthLayout = new javax.swing.GroupLayout(pmenunorth);
        pmenunorth.setLayout(pmenunorthLayout);
        pmenunorthLayout.setHorizontalGroup(
            pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmenunorthLayout.createSequentialGroup()
                .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pmenunorthLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pmenunorthLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(l1)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmenunorthLayout.createSequentialGroup()
                                .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lquyenacc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addGroup(pmenunorthLayout.createSequentialGroup()
                                        .addComponent(lhi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lacc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26))))
                    .addGroup(pmenunorthLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l4)
                            .addComponent(l3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap())
        );
        pmenunorthLayout.setVerticalGroup(
            pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmenunorthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lhi)
                    .addComponent(lacc, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lquyenacc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pmenu.add(pmenunorth, java.awt.BorderLayout.NORTH);

        pmenucenter.setPreferredSize(new java.awt.Dimension(200, 400));
        pmenucenter.setLayout(new java.awt.BorderLayout());

        pbcenter1.setPreferredSize(new java.awt.Dimension(200, 250));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Hóa đơn bán hàng trực tiếp");

        bhoadon.setText("Tạo hóa đơn");
        bhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhoadonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Cập nhật đơn đặt hàng qua mạng");

        bcapnhat.setText("Cập nhật");
        bcapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcapnhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pbcenter1Layout = new javax.swing.GroupLayout(pbcenter1);
        pbcenter1.setLayout(pbcenter1Layout);
        pbcenter1Layout.setHorizontalGroup(
            pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbcenter1Layout.createSequentialGroup()
                .addGroup(pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(bcapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(bhoadon)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pbcenter1Layout.setVerticalGroup(
            pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbcenter1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bhoadon)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(bcapnhat)
                .addGap(87, 87, 87))
        );

        pmenucenter.add(pbcenter1, java.awt.BorderLayout.NORTH);

        pmenu.add(pmenucenter, java.awt.BorderLayout.CENTER);

        pmenusouth.setLayout(new java.awt.BorderLayout());

        pmenusouth1.setPreferredSize(new java.awt.Dimension(200, 100));

        bexit.setText("Exit");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        jProgressBar2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pmenusouth1Layout = new javax.swing.GroupLayout(pmenusouth1);
        pmenusouth1.setLayout(pmenusouth1Layout);
        pmenusouth1Layout.setHorizontalGroup(
            pmenusouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmenusouth1Layout.createSequentialGroup()
                .addGroup(pmenusouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pmenusouth1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pmenusouth1Layout.setVerticalGroup(
            pmenusouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmenusouth1Layout.createSequentialGroup()
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bexit)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pmenusouth.add(pmenusouth1, java.awt.BorderLayout.SOUTH);

        pmenu.add(pmenusouth, java.awt.BorderLayout.PAGE_END);

        fbanhang.getContentPane().add(pmenu, java.awt.BorderLayout.WEST);

        pchinh.setMinimumSize(new java.awt.Dimension(600, 600));
        pchinh.setPreferredSize(new java.awt.Dimension(600, 600));

        pcenter.setMinimumSize(new java.awt.Dimension(590, 600));
        pcenter.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pchinhLayout = new javax.swing.GroupLayout(pchinh);
        pchinh.setLayout(pchinhLayout);
        pchinhLayout.setHorizontalGroup(
            pchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pchinhLayout.createSequentialGroup()
                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(598, Short.MAX_VALUE))
            .addGroup(pchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pchinhLayout.createSequentialGroup()
                    .addGap(0, 300, Short.MAX_VALUE)
                    .addComponent(pcenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 300, Short.MAX_VALUE)))
        );
        pchinhLayout.setVerticalGroup(
            pchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pchinhLayout.createSequentialGroup()
                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pchinhLayout.createSequentialGroup()
                    .addGap(0, 350, Short.MAX_VALUE)
                    .addComponent(pcenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 250, Short.MAX_VALUE)))
        );

        fbanhang.getContentPane().add(pchinh, java.awt.BorderLayout.CENTER);

        dyeucaugiaohang.setMinimumSize(new java.awt.Dimension(400, 400));

        jLabel20.setText(".........................................");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel21.setForeground(new java.awt.Color(0, 0, 255));
        jLabel21.setText("Số đt di động");

        jLabel18.setText(".........................................");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("Số đt cố định");

        jLabel26.setText(" ");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel27.setForeground(new java.awt.Color(0, 102, 102));
        jLabel27.setText("Tông số tiền ");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("VND");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("0");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel30.setForeground(new java.awt.Color(255, 0, 204));
        jLabel30.setText("Lưu ý: Nhân viên nhận thanh toán trước khi giao hàng.");

        jButton4.setText("Hoàn tất");

        jButton5.setText("Hủy");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel15.setText("........................................");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Họ tên khách hàng");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel25.setForeground(new java.awt.Color(0, 0, 255));
        jLabel25.setText("Nhân viên bán hàng");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("Địa chỉ");

        jLabel24.setText("........................................");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel23.setForeground(new java.awt.Color(0, 0, 255));
        jLabel23.setText("Loại hàng và số lượng");

        jLabel22.setText("........................................");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Hóa đơn giao hàng tại nhà");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel17)
                            .addComponent(jLabel23)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel21))
                            .addComponent(jLabel25))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(jTextField1)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel18)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dyeucaugiaohang.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton2.setText("Hoàn tất");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lcbdiachi.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lcbdiachi.setForeground(new java.awt.Color(204, 0, 0));
        lcbdiachi.setText(" ");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Số điện thoại");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Số loại hàng mua");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Họ tên khách hàng");

        jButton1.setText("Liệt kê ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Tổng số tiền cần thanh toán");

        tongtien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tongtien.setText("0");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Địa chỉ");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("Người bán");

        jButton3.setText("Hủy bỏ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Yêu cầu giao hàng");

        lcbnv.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lcbnv.setForeground(new java.awt.Color(204, 0, 0));
        lcbnv.setText(" ");

        lcbkhachhang.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lcbkhachhang.setForeground(new java.awt.Color(204, 0, 0));
        lcbkhachhang.setText(" ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("VND");

        lhangmua.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lhangmua.setForeground(new java.awt.Color(255, 0, 51));
        lhangmua.setText(" ");

        javax.swing.GroupLayout pbanhangLayout = new javax.swing.GroupLayout(pbanhang);
        pbanhang.setLayout(pbanhangLayout);
        pbanhangLayout.setHorizontalGroup(
            pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbanhangLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pbanhangLayout.createSequentialGroup()
                        .addGroup(pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pbanhangLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pbanhangLayout.createSequentialGroup()
                                .addGroup(pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel12))
                                .addGroup(pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pbanhangLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfnv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                            .addComponent(tfdiachi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                            .addComponent(lcbkhachhang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                            .addComponent(tfkhachhang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                            .addComponent(lcbdiachi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                            .addComponent(tfsdt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                            .addComponent(lcbnv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                            .addComponent(lhangmua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)))
                                    .addGroup(pbanhangLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jButton1)))))
                        .addGap(77, 77, 77))
                    .addGroup(pbanhangLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pbanhangLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        pbanhangLayout.setVerticalGroup(
            pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbanhangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addGroup(pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcbkhachhang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcbdiachi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcbnv)
                .addGap(14, 14, 14)
                .addGroup(pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lhangmua)
                .addGap(25, 25, 25)
                .addGroup(pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tongtien)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35)
                .addGroup(pbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Họ tên", "Địa chỉ", "Số đt cố định", "Số đt di động", "Loại hàng vá số lượng", "Yêu cầu khác", "Chứng thực"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Đơn đặt hàng qua mạng");

        bchuyentiep.setText("Chuyển tiếp");
        bchuyentiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bchuyentiepActionPerformed(evt);
            }
        });

        bhuydon.setText("Hủy đơn");

        javax.swing.GroupLayout pdonhangLayout = new javax.swing.GroupLayout(pdonhang);
        pdonhang.setLayout(pdonhangLayout);
        pdonhangLayout.setHorizontalGroup(
            pdonhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pdonhangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pdonhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pdonhangLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel9)
                        .addContainerGap(215, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pdonhangLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                        .addComponent(bchuyentiep)
                        .addGap(28, 28, 28)
                        .addComponent(bhuydon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        pdonhangLayout.setVerticalGroup(
            pdonhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdonhangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pdonhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bchuyentiep)
                    .addComponent(bhuydon))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 51));
        jLabel31.setText("Liệt kê hàng cần mua");

        jButton6.setText("Kiểm tra");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 204));
        jLabel32.setText("Mã hàng");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 204));
        jLabel33.setText("Số lượng");

        jButton7.setText("Tiếp");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Hoàn tất");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout flietkeLayout = new javax.swing.GroupLayout(flietke.getContentPane());
        flietke.getContentPane().setLayout(flietkeLayout);
        flietkeLayout.setHorizontalGroup(
            flietkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, flietkeLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(flietkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(flietkeLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(tfsl))
                    .addGroup(flietkeLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)
                        .addComponent(tfktma, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(flietkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addGroup(flietkeLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButton8)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(flietkeLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel31)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        flietkeLayout.setVerticalGroup(
            flietkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flietkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(flietkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(tfktma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(flietkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tfsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Mã hàng tồn tại mời nhập số lượng mua.");

        jButton9.setText("OK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dkiemtramaLayout = new javax.swing.GroupLayout(dkiemtrama.getContentPane());
        dkiemtrama.getContentPane().setLayout(dkiemtramaLayout);
        dkiemtramaLayout.setHorizontalGroup(
            dkiemtramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkiemtramaLayout.createSequentialGroup()
                .addGroup(dkiemtramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dkiemtramaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                    .addGroup(dkiemtramaLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dkiemtramaLayout.setVerticalGroup(
            dkiemtramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkiemtramaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(23, 23, 23))
        );

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 0, 51));
        jLabel34.setText("Mã hàng này không tồn tại");

        jButton10.setText("OK");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dmasaiLayout = new javax.swing.GroupLayout(dmasai.getContentPane());
        dmasai.getContentPane().setLayout(dmasaiLayout);
        dmasaiLayout.setHorizontalGroup(
            dmasaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dmasaiLayout.createSequentialGroup()
                .addGroup(dmasaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dmasaiLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dmasaiLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        dmasaiLayout.setVerticalGroup(
            dmasaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dmasaiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel34)
                .addGap(26, 26, 26)
                .addComponent(jButton10)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        dketnoi.setTitle("Lỗi kết nối");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel35.setForeground(new java.awt.Color(255, 0, 0));
        jLabel35.setText("Không thể kết nối tới Server");

        jButton11.setText("OK");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dketnoiLayout = new javax.swing.GroupLayout(dketnoi.getContentPane());
        dketnoi.getContentPane().setLayout(dketnoiLayout);
        dketnoiLayout.setHorizontalGroup(
            dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dketnoiLayout.createSequentialGroup()
                .addGroup(dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dketnoiLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel35))
                    .addGroup(dketnoiLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        dketnoiLayout.setVerticalGroup(
            dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dketnoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        System.exit(1);
}//GEN-LAST:event_bexitActionPerformed

    private void bhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhoadonActionPerformed
       hang="";
       tien=0;
       lhangmua.setText("");
       tongtien.setText("");
       tfkhachhang.setText("");
       tfdiachi.setText("");
       tfsdt.setText("");
       tfnv.setText("");
       pcenter.removeAll();
       fbanhang.pack();
       pcenter.add(pbanhang,java.awt.BorderLayout.NORTH);
       fbanhang.pack();
    }//GEN-LAST:event_bhoadonActionPerformed

    private void bcapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcapnhatActionPerformed
       pcenter.removeAll();
       fbanhang.pack();
       pcenter.add(pdonhang,java.awt.BorderLayout.NORTH);
       fbanhang.pack();
    }//GEN-LAST:event_bcapnhatActionPerformed

    private void bchuyentiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bchuyentiepActionPerformed
        dyeucaugiaohang.pack();
        dyeucaugiaohang.setVisible(true);
    }//GEN-LAST:event_bchuyentiepActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dyeucaugiaohang.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pcenter.removeAll();
        fbanhang.pack();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        flietke.pack();
        flietke.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
                Serverconnection1 = (Control.RemoteServer)Naming.lookup("rmi://"+ip+":1099/Server");
                s2=Serverconnection1.data("ktma",tfktma.getText(),"","","","","","","","","");
                if(s2[0].equals("tontai")){
                    dkiemtrama.pack();
                    dkiemtrama.setVisible(true);
                }
                if(s2[0].equals("khongtontai")){
                    dmasai.pack();
                    dmasai.setVisible(true);
                }
            }
            catch(Exception e){
                dketnoi.pack();
                dketnoi.setVisible(true);
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        hangmua=s2[1];
        dkiemtrama.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        tfktma.setText("");
        dmasai.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        tien=tien+Integer.parseInt(tfsl.getText())*Long.parseLong(s2[2]);
        hang=hang+hangmua+" số lượng "+tfsl.getText()+"; ";
        lhangmua.setText("");
        lhangmua.setText(hang);
        tongtien.setText(String.valueOf(tien));
        tfktma.setText("");
        tfsl.setText("");

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        flietke.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lcbkhachhang.setText("");
        lcbdiachi.setText("");
        lcbnv.setText("");
        boolean check=true;
        if(new hamgoi().ktString(tfkhachhang.getText())==false){
            lcbkhachhang.setText("* Bat buoc phai nhap thong tin nay");
            check=false;
        }
        if(new hamgoi().ktString(tfdiachi.getText())==false){
            lcbdiachi.setText("* Bat buoc phai nhap thong tin nay");
            check=false;
        }
        if(new hamgoi().ktString(tfnv.getText())==false){
            lcbnv.setText("* Bat buoc phai nhap thong tin nay");
            check=false;
        }
        if(check==true){
            try{
                Serverconnection1 = (Control.RemoteServer)Naming.lookup("rmi://"+ip+":1099/Server");
                s2=Serverconnection1.data("giaohangoff",tfkhachhang.getText(),tfdiachi.getText(),tfsdt.getText(),tfnv.getText(),lhangmua.getText(),tongtien.getText(),"","","","");
                if(s2[0].equals("thanhcong")==true){
                    javax.swing.JOptionPane.showMessageDialog(thongbaothanhcong, "Thông tin loại hàng mới đã được đưa vào kho.");
                    pcenter.removeAll();
                    fbanhang.pack();
                }

            }
            catch(Exception e){
                dketnoi.pack();
                dketnoi.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        dketnoi.setVisible(false);
}//GEN-LAST:event_jButton11ActionPerformed
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               //new Login().abc();

                new fbanhang().fbanhang.pack();
                new fbanhang().fbanhang.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcapnhat;
    private javax.swing.JButton bchuyentiep;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bhoadon;
    private javax.swing.JButton bhuydon;
    private javax.swing.JDialog dketnoi;
    private javax.swing.JDialog dkiemtrama;
    private javax.swing.JDialog dmasai;
    private javax.swing.JDialog dyeucaugiaohang;
    public javax.swing.JFrame fbanhang;
    private javax.swing.JFrame flietke;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel lacc;
    private javax.swing.JLabel lcbdiachi;
    private javax.swing.JLabel lcbkhachhang;
    private javax.swing.JLabel lcbnv;
    private javax.swing.JLabel lhangmua;
    private javax.swing.JLabel lhi;
    private javax.swing.JLabel lquyenacc;
    private java.awt.Panel pbanhang;
    private javax.swing.JPanel pbcenter1;
    private javax.swing.JPanel pcenter;
    private javax.swing.JPanel pchinh;
    private java.awt.Panel pdonhang;
    private javax.swing.JPanel pmenu;
    private javax.swing.JPanel pmenucenter;
    private javax.swing.JPanel pmenunorth;
    private javax.swing.JPanel pmenusouth;
    private javax.swing.JPanel pmenusouth1;
    private javax.swing.JTextField tfdiachi;
    private javax.swing.JTextField tfkhachhang;
    private javax.swing.JTextField tfktma;
    private javax.swing.JTextField tfnv;
    private javax.swing.JTextField tfsdt;
    private javax.swing.JTextField tfsl;
    private javax.swing.JOptionPane thongbaothanhcong;
    private javax.swing.JLabel tongtien;
    // End of variables declaration//GEN-END:variables

}
