/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fgiaohang.java
 *
 * Created on Apr 28, 2010, 12:36:24 AM
 */

package banhang;
import java.rmi.Naming;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Duc
 */
public class fgiaohang extends javax.swing.JFrame {
    private Control.RemoteServer Serverconnection1;
    String ip=new hamgoi().docip();
    String[] s2=new String[11];
    String ten,diachi,sdt,nguoigiao,hangmua,tien,ID;
    /** Creates new form fgiaohang */
    public fgiaohang() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fgiaohang = new javax.swing.JFrame();
        pmenu = new javax.swing.JPanel();
        pmenunorth = new javax.swing.JPanel();
        lquyenacc = new javax.swing.JLabel();
        lhi = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lacc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pmenucenter = new javax.swing.JPanel();
        pbcenter1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bgiaohangtructiep = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bgiaohangtainha = new javax.swing.JButton();
        pmenusouth = new javax.swing.JPanel();
        pmenusouth1 = new javax.swing.JPanel();
        bexit = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        pchinh = new javax.swing.JPanel();
        jProgressBar3 = new javax.swing.JProgressBar();
        pcenter = new javax.swing.JPanel();
        pgiaohangtructiep = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pgiaohangtainha = new java.awt.Panel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        fnguoigiao = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfnvgiao = new javax.swing.JTextField();
        cbten = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        thongbaothanhcong = new javax.swing.JOptionPane();
        dketnoi = new javax.swing.JDialog(fnguoigiao,true);
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        fgiaohang.setTitle("Quản lý giao hàng");
        fgiaohang.setMinimumSize(new java.awt.Dimension(800, 600));
        fgiaohang.setResizable(false);

        pmenu.setPreferredSize(new java.awt.Dimension(250, 650));
        pmenu.setRequestFocusEnabled(false);
        pmenu.setLayout(new java.awt.BorderLayout());

        pmenunorth.setPreferredSize(new java.awt.Dimension(200, 180));

        lquyenacc.setForeground(new java.awt.Color(0, 0, 255));
        lquyenacc.setText("Bạn đang đăng nhập với quyền giao hàng");

        lhi.setFont(new java.awt.Font("Times New Roman", 1, 12));
        lhi.setForeground(new java.awt.Color(255, 0, 51));
        lhi.setText("Xin chào");

        l1.setText("Bạn có quyền quản lý");

        l3.setText("1> Giao hàng trực tiếp cho khách.");

        l4.setText("2> Giao hàng tại nhà.");

        jProgressBar1.setBackground(new java.awt.Color(204, 204, 204));

        lacc.setFont(new java.awt.Font("Times New Roman", 1, 14));
        lacc.setForeground(new java.awt.Color(255, 0, 153));
        lacc.setText(new hamgoi().docusername());

        jLabel3.setText("3> Xác nhận hoàn tất hóa đơn.");

        javax.swing.GroupLayout pmenunorthLayout = new javax.swing.GroupLayout(pmenunorth);
        pmenunorth.setLayout(pmenunorthLayout);
        pmenunorthLayout.setHorizontalGroup(
            pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmenunorthLayout.createSequentialGroup()
                .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pmenunorthLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(l1)
                        .addGap(83, 83, 83))
                    .addGroup(pmenunorthLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l3)
                            .addComponent(l4)
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmenunorthLayout.createSequentialGroup()
                        .addContainerGap(51, Short.MAX_VALUE)
                        .addComponent(lhi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lacc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(pmenunorthLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lquyenacc, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pmenunorthLayout.setVerticalGroup(
            pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmenunorthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lhi)
                    .addComponent(lacc, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lquyenacc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1)
                .addGap(18, 18, 18)
                .addComponent(l3)
                .addGap(11, 11, 11)
                .addComponent(l4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pmenu.add(pmenunorth, java.awt.BorderLayout.NORTH);

        pmenucenter.setPreferredSize(new java.awt.Dimension(200, 400));
        pmenucenter.setLayout(new java.awt.BorderLayout());

        pbcenter1.setPreferredSize(new java.awt.Dimension(200, 250));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Yêu cầu giao hàng trưc tiếp.");

        bgiaohangtructiep.setText("Cập nhật");
        bgiaohangtructiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgiaohangtructiepActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Yêu cầu giao hàng tại nhà.");

        bgiaohangtainha.setText("Cập nhật");
        bgiaohangtainha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgiaohangtainhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pbcenter1Layout = new javax.swing.GroupLayout(pbcenter1);
        pbcenter1.setLayout(pbcenter1Layout);
        pbcenter1Layout.setHorizontalGroup(
            pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbcenter1Layout.createSequentialGroup()
                .addGroup(pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(bgiaohangtainha, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(bgiaohangtructiep, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pbcenter1Layout.setVerticalGroup(
            pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pbcenter1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bgiaohangtructiep)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(bgiaohangtainha)
                .addGap(87, 87, 87))
        );

        pmenucenter.add(pbcenter1, java.awt.BorderLayout.NORTH);

        pmenu.add(pmenucenter, java.awt.BorderLayout.CENTER);

        pmenusouth.setLayout(new java.awt.BorderLayout());

        pmenusouth1.setPreferredSize(new java.awt.Dimension(200, 100));

        bexit.setText("Exit");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        jProgressBar2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pmenusouth1Layout = new javax.swing.GroupLayout(pmenusouth1);
        pmenusouth1.setLayout(pmenusouth1Layout);
        pmenusouth1Layout.setHorizontalGroup(
            pmenusouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmenusouth1Layout.createSequentialGroup()
                .addGroup(pmenusouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pmenusouth1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pmenusouth1Layout.setVerticalGroup(
            pmenusouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmenusouth1Layout.createSequentialGroup()
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bexit)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pmenusouth.add(pmenusouth1, java.awt.BorderLayout.SOUTH);

        pmenu.add(pmenusouth, java.awt.BorderLayout.PAGE_END);

        fgiaohang.getContentPane().add(pmenu, java.awt.BorderLayout.WEST);

        pchinh.setMinimumSize(new java.awt.Dimension(600, 600));
        pchinh.setPreferredSize(new java.awt.Dimension(620, 650));

        pcenter.setMinimumSize(new java.awt.Dimension(590, 600));
        pcenter.setPreferredSize(new java.awt.Dimension(600, 650));
        pcenter.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pchinhLayout = new javax.swing.GroupLayout(pchinh);
        pchinh.setLayout(pchinhLayout);
        pchinhLayout.setHorizontalGroup(
            pchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pchinhLayout.createSequentialGroup()
                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pcenter, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
        );
        pchinhLayout.setVerticalGroup(
            pchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pchinhLayout.createSequentialGroup()
                .addGroup(pchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fgiaohang.getContentPane().add(pchinh, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Yêu cầu giao hàng.");

        tb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ tên khách hàng", "Địa chỉ", "Số đt", "Người bán", "Loại hàng mua", "Tổng tiền", "ID phiếu giao hàng"
            }
        ));
        jScrollPane1.setViewportView(tb3);

        jButton1.setText("Đã giao hàng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cập nhật");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pgiaohangtructiepLayout = new javax.swing.GroupLayout(pgiaohangtructiep);
        pgiaohangtructiep.setLayout(pgiaohangtructiepLayout);
        pgiaohangtructiepLayout.setHorizontalGroup(
            pgiaohangtructiepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgiaohangtructiepLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(pgiaohangtructiepLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addContainerGap(214, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        pgiaohangtructiepLayout.setVerticalGroup(
            pgiaohangtructiepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgiaohangtructiepLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pgiaohangtructiepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(31, 31, 31))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Yêu cầu giao hàng tại nhà.");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Họ tên khách hàng", "Địa chỉ", "Số đt cố định", "Số đt di động", "Các loại hàng đã  đặt mua", "Tổng số tiền", "Đã thanh toán", "Đã giao hàng"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Hoàn tất");

        jButton4.setText("Cập nhật");

        jButton5.setText("Hủy đơn");

        javax.swing.GroupLayout pgiaohangtainhaLayout = new javax.swing.GroupLayout(pgiaohangtainha);
        pgiaohangtainha.setLayout(pgiaohangtainhaLayout);
        pgiaohangtainhaLayout.setHorizontalGroup(
            pgiaohangtainhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgiaohangtainhaLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(200, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
            .addGroup(pgiaohangtainhaLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel5)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        pgiaohangtainhaLayout.setVerticalGroup(
            pgiaohangtainhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgiaohangtainhaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pgiaohangtainhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(31, 31, 31))
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Nhân viên xác nhận đã giao hàng");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Nhân viên giao hàng ");

        cbten.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        cbten.setForeground(new java.awt.Color(204, 0, 51));
        cbten.setText(" ");

        jButton6.setText("Xác nhận");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fnguoigiaoLayout = new javax.swing.GroupLayout(fnguoigiao.getContentPane());
        fnguoigiao.getContentPane().setLayout(fnguoigiaoLayout);
        fnguoigiaoLayout.setHorizontalGroup(
            fnguoigiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fnguoigiaoLayout.createSequentialGroup()
                .addGroup(fnguoigiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fnguoigiaoLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel6))
                    .addGroup(fnguoigiaoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fnguoigiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbten, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(tfnvgiao, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                    .addGroup(fnguoigiaoLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        fnguoigiaoLayout.setVerticalGroup(
            fnguoigiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fnguoigiaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(fnguoigiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfnvgiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        dketnoi.setTitle("Lỗi kết nối");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Không thể kết nối tới Server");

        jButton8.setText("OK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dketnoiLayout = new javax.swing.GroupLayout(dketnoi.getContentPane());
        dketnoi.getContentPane().setLayout(dketnoiLayout);
        dketnoiLayout.setHorizontalGroup(
            dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dketnoiLayout.createSequentialGroup()
                .addGroup(dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dketnoiLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10))
                    .addGroup(dketnoiLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        dketnoiLayout.setVerticalGroup(
            dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dketnoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bgiaohangtructiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgiaohangtructiepActionPerformed
        pcenter.removeAll();
        fgiaohang.pack();
        pcenter.add(pgiaohangtructiep,java.awt.BorderLayout.WEST);
        fgiaohang.pack();
}//GEN-LAST:event_bgiaohangtructiepActionPerformed

    private void bgiaohangtainhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgiaohangtainhaActionPerformed
        pcenter.removeAll();
        fgiaohang.pack();
        pcenter.add(pgiaohangtainha,java.awt.BorderLayout.WEST);
        fgiaohang.pack();
}//GEN-LAST:event_bgiaohangtainhaActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        System.exit(1);
}//GEN-LAST:event_bexitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model=(DefaultTableModel)tb3.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            ten="";
            diachi="";
            sdt="";
            hangmua="";
            tien="";
            Serverconnection1 = (Control.RemoteServer)Naming.lookup("rmi://"+ip+":1099/Server");
            s2=Serverconnection1.data("capnhatoff","","","","","","","","","","");
            model.addRow(new Object[] {s2[1],s2[2],s2[3],s2[4],s2[5],s2[6],s2[7]});
            ten=s2[1];
            diachi=s2[2];
            sdt=s2[3];
            hangmua=s2[5];
            tien=s2[6];
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cbten.setText("");
        tfnvgiao.setText("");
        fnguoigiao.pack();
        fnguoigiao.setVisible(true);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //DefaultTableModel model=(DefaultTableModel)tb3.getModel();
        //model.getDataVector().removeAllElements();
        //model.fireTableDataChanged();
        boolean check=true;
        try{
            if(new hamgoi().ktString(tfnvgiao.getText())==false){
                cbten.setText("* Bắt buộc phải nhập thông tin này!");
                    check=false;
            }
            if(check==true){
                System.out.println(ten+diachi+sdt+tfnvgiao.getText()+hangmua+tien);
                Serverconnection1 = (Control.RemoteServer)Naming.lookup("rmi://"+ip+":1099/Server");
                s2=Serverconnection1.data("luuhoadon",ten,diachi,sdt,tfnvgiao.getText(),hangmua,tien,"","","","");
                if(s2[0].equals("thanhcong")==true){                
                    javax.swing.JOptionPane.showMessageDialog(thongbaothanhcong, "Hóa đơn đầy đủ đã được lưu vào CSDL.");
                    //model.getDataVector().removeAllElements();
                }
                fnguoigiao.setVisible(false);
            }
        }
        catch(Exception e){
            System.out.print(e);
            dketnoi.pack();
            dketnoi.setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dketnoi.setVisible(false);
}//GEN-LAST:event_jButton8ActionPerformed
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               //new Login().abc();

                new fgiaohang().fgiaohang.pack();
                new fgiaohang().fgiaohang.setVisible(true);
            }
        });
    }
    /**
    * @param args the command line arguments
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexit;
    private javax.swing.JButton bgiaohangtainha;
    private javax.swing.JButton bgiaohangtructiep;
    private javax.swing.JLabel cbten;
    private javax.swing.JDialog dketnoi;
    public javax.swing.JFrame fgiaohang;
    private javax.swing.JFrame fnguoigiao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel lacc;
    private javax.swing.JLabel lhi;
    private javax.swing.JLabel lquyenacc;
    private javax.swing.JPanel pbcenter1;
    private javax.swing.JPanel pcenter;
    private javax.swing.JPanel pchinh;
    private java.awt.Panel pgiaohangtainha;
    private java.awt.Panel pgiaohangtructiep;
    private javax.swing.JPanel pmenu;
    private javax.swing.JPanel pmenucenter;
    private javax.swing.JPanel pmenunorth;
    private javax.swing.JPanel pmenusouth;
    private javax.swing.JPanel pmenusouth1;
    private javax.swing.JTable tb3;
    private javax.swing.JTextField tfnvgiao;
    private javax.swing.JOptionPane thongbaothanhcong;
    // End of variables declaration//GEN-END:variables

}
