/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Apr 17, 2010, 9:07:09 PM
 */

package banhang;
import java.rmi.Naming;
/**
 *
 * @author Duc
 */
public class flogin extends javax.swing.JFrame {
    String ip=new hamgoi().docip();
    private Control.RemoteServer Serverconnection;
    /** Creates new form Login */
    public flogin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dketnoi = new javax.swing.JDialog(flogin,true);
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        dthongbao = new javax.swing.JDialog(flogin,true);
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        dadmin = new javax.swing.JDialog(flogin,true);
        jLabel6 = new javax.swing.JLabel();
        bxacnhanadmin = new javax.swing.JButton();
        flogin = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        blogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lcbusername = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lcbpasswork = new javax.swing.JLabel();
        tfpassword = new javax.swing.JPasswordField();
        dxacnhanbanhang = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dxacnhankhohang = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        dxacnhangiaohang = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        dketnoi.setTitle("Lỗi kết nối");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Không thể kết nối tới Server");

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dketnoiLayout = new javax.swing.GroupLayout(dketnoi.getContentPane());
        dketnoi.getContentPane().setLayout(dketnoiLayout);
        dketnoiLayout.setHorizontalGroup(
            dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dketnoiLayout.createSequentialGroup()
                .addGroup(dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dketnoiLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5))
                    .addGroup(dketnoiLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        dketnoiLayout.setVerticalGroup(
            dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dketnoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Account chưa được đăng ký hoặc password chưa chính xác");

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dthongbaoLayout = new javax.swing.GroupLayout(dthongbao.getContentPane());
        dthongbao.getContentPane().setLayout(dthongbaoLayout);
        dthongbaoLayout.setHorizontalGroup(
            dthongbaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dthongbaoLayout.createSequentialGroup()
                .addGroup(dthongbaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dthongbaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(dthongbaoLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dthongbaoLayout.setVerticalGroup(
            dthongbaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dthongbaoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        dadmin.setTitle("Đăng nhập thanh công");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Bạn vừa đăng nhập với account phân quyền admin");

        bxacnhanadmin.setText("OK");
        bxacnhanadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxacnhanadminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dadminLayout = new javax.swing.GroupLayout(dadmin.getContentPane());
        dadmin.getContentPane().setLayout(dadminLayout);
        dadminLayout.setHorizontalGroup(
            dadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadminLayout.createSequentialGroup()
                .addGroup(dadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadminLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6))
                    .addGroup(dadminLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(bxacnhanadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dadminLayout.setVerticalGroup(
            dadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(bxacnhanadmin)
                .addContainerGap())
        );

        flogin.setTitle("LOGIN");
        flogin.setMinimumSize(new java.awt.Dimension(337, 220));
        flogin.setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Username");

        blogin.setText("Login");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Login");

        jButton2.setText("Canel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lcbusername.setFont(new java.awt.Font("Times New Roman", 2, 12));
        lcbusername.setForeground(new java.awt.Color(255, 0, 0));
        lcbusername.setText(" ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Password");

        lcbpasswork.setFont(new java.awt.Font("Times New Roman", 2, 12));
        lcbpasswork.setForeground(new java.awt.Color(255, 0, 0));
        lcbpasswork.setText(" ");

        javax.swing.GroupLayout floginLayout = new javax.swing.GroupLayout(flogin.getContentPane());
        flogin.getContentPane().setLayout(floginLayout);
        floginLayout.setHorizontalGroup(
            floginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, floginLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(143, 143, 143))
            .addGroup(floginLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(floginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(floginLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(blogin, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, floginLayout.createSequentialGroup()
                        .addGroup(floginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(floginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfusername, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(lcbusername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(floginLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lcbpasswork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tfpassword, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        floginLayout.setVerticalGroup(
            floginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floginLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(floginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcbusername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(floginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcbpasswork)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(floginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blogin)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Bạn vừa đăng nhập với account quyền bán hàng");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dxacnhanbanhangLayout = new javax.swing.GroupLayout(dxacnhanbanhang.getContentPane());
        dxacnhanbanhang.getContentPane().setLayout(dxacnhanbanhangLayout);
        dxacnhanbanhangLayout.setHorizontalGroup(
            dxacnhanbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dxacnhanbanhangLayout.createSequentialGroup()
                .addGroup(dxacnhanbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dxacnhanbanhangLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7))
                    .addGroup(dxacnhanbanhangLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dxacnhanbanhangLayout.setVerticalGroup(
            dxacnhanbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dxacnhanbanhangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Bạn vừa đăng nhập với account quyền quản lý kho hàng");

        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dxacnhankhohangLayout = new javax.swing.GroupLayout(dxacnhankhohang.getContentPane());
        dxacnhankhohang.getContentPane().setLayout(dxacnhankhohangLayout);
        dxacnhankhohangLayout.setHorizontalGroup(
            dxacnhankhohangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dxacnhankhohangLayout.createSequentialGroup()
                .addGroup(dxacnhankhohangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dxacnhankhohangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(dxacnhankhohangLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dxacnhankhohangLayout.setVerticalGroup(
            dxacnhankhohangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dxacnhankhohangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Bạn vừa đăng nhập với account quyền giao hàng");

        jButton6.setText("OK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dxacnhangiaohangLayout = new javax.swing.GroupLayout(dxacnhangiaohang.getContentPane());
        dxacnhangiaohang.getContentPane().setLayout(dxacnhangiaohangLayout);
        dxacnhangiaohangLayout.setHorizontalGroup(
            dxacnhangiaohangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dxacnhangiaohangLayout.createSequentialGroup()
                .addGroup(dxacnhangiaohangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dxacnhangiaohangLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8))
                    .addGroup(dxacnhangiaohangLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        dxacnhangiaohangLayout.setVerticalGroup(
            dxacnhangiaohangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dxacnhangiaohangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dketnoi.setVisible(false);
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dthongbao.setVisible(false);
}//GEN-LAST:event_jButton3ActionPerformed

    private void bxacnhanadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxacnhanadminActionPerformed
        dadmin.setVisible(false);
        new fadmin().fadmin.pack();
        new fadmin().fadmin.setVisible(true);
}//GEN-LAST:event_bxacnhanadminActionPerformed

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        boolean check=true;
        lcbusername.setText(" ");
        lcbpasswork.setText(" ");
        new hamgoi().ghiusername(tfusername.getText());
        if(new hamgoi().ktString(tfusername.getText().trim())==false){
            lcbusername.setText("Bạn hãy nhập username!");
            check=false;
        }
        if(new hamgoi().ktString(tfpassword.getText().trim())==false){
            lcbpasswork.setText("Bạn hãy nhập password!");
            check=false;
        }
        if(check==true){
            try{
                 String[] s1=new String[11];
                String s="";
                s=tfusername.getText().trim()+";"+tfpassword.getText().trim();
                if(s.equals("admin;trongjdduwcs")){
                    flogin.setVisible(false);
                    dadmin.pack();
                    dadmin.setVisible(true);
                } 
                else{
                    Serverconnection = (Control.RemoteServer)Naming.lookup("rmi://"+ip+":1099/Server");
                    s1=Serverconnection.data("ktaccount",s,"","","","","","","","","");
                    if(s1[0].equals("admin")){
                    flogin.setVisible(false);
                    dadmin.pack();
                    dadmin.setVisible(true);
                    }
                    else if(s1[0].equals("banhang")){
                        flogin.setVisible(false);
                        dxacnhanbanhang.pack();
                        dxacnhanbanhang.setVisible(true);
                    }
                    else if(s1[0].equals("khohang")){
                        flogin.setVisible(false);
                        dxacnhankhohang.pack();
                        dxacnhankhohang.setVisible(true);
                    }
                    else if(s1[0].equals("giaohang")){
                        flogin.setVisible(false);
                        dxacnhangiaohang.pack();
                        dxacnhangiaohang.setVisible(true);
                    }
                    else{
                        dthongbao.pack();
                        dthongbao.setVisible(true);
                    }
                }
            } catch(Exception e){
                dketnoi.pack();
                dketnoi.setVisible(true);
            }
        }
}//GEN-LAST:event_bloginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(1);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dxacnhanbanhang.setVisible(false);
        new fbanhang().fbanhang.pack();
        new fbanhang().fbanhang.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dxacnhankhohang.setVisible(false);
        new fnhapkho().fkhohang.pack();
        new fnhapkho().fkhohang.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       dxacnhangiaohang.setVisible(false);
       new fgiaohang().fgiaohang.pack();
       new fgiaohang().fgiaohang.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed
    /**
    * @param args the command line arguments
    */public void abc(){
        String[] a=new String[11];
        try{
         Serverconnection = (Control.RemoteServer)Naming.lookup("rmi://"+ip+":1099/Server");
         Serverconnection.data("taoaccount","duc","123","Duc","m1","admin","","","","","");
        }
        catch(Exception e){}
    }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               //new Login().abc();
                
                new flogin().flogin.pack();
                new flogin().flogin.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blogin;
    private javax.swing.JButton bxacnhanadmin;
    private javax.swing.JDialog dadmin;
    private javax.swing.JDialog dketnoi;
    private javax.swing.JDialog dthongbao;
    private javax.swing.JDialog dxacnhanbanhang;
    private javax.swing.JDialog dxacnhangiaohang;
    private javax.swing.JDialog dxacnhankhohang;
    public javax.swing.JFrame flogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lcbpasswork;
    private javax.swing.JLabel lcbusername;
    private javax.swing.JPasswordField tfpassword;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables

}
