/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fnhapkho.java
 *
 * Created on Apr 27, 2010, 8:32:51 PM
 */

package banhang;
import java.rmi.Naming;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Duc
 */
public class fnhapkho extends javax.swing.JFrame {
    private Control.RemoteServer Serverconnection1;
    String ip=new hamgoi().docip();
    String[] s2=new String[11];
    /** Creates new form fnhapkho */
    public fnhapkho() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fkhohang = new javax.swing.JFrame();
        pmenu = new javax.swing.JPanel();
        pmenunorth = new javax.swing.JPanel();
        lquyenacc = new javax.swing.JLabel();
        lhi = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lacc = new javax.swing.JLabel();
        pmenucenter = new javax.swing.JPanel();
        pbcenter1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bnhap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bquanly = new javax.swing.JButton();
        pmenusouth = new javax.swing.JPanel();
        pmenusouth1 = new javax.swing.JPanel();
        bexit = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        pchinh = new javax.swing.JPanel();
        jProgressBar3 = new javax.swing.JProgressBar();
        pcenter = new javax.swing.JPanel();
        pnhapkho = new java.awt.Panel();
        jLabel9 = new javax.swing.JLabel();
        cbten = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbgianhap = new javax.swing.JLabel();
        tfgianhap = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfgiaban = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cbgiaban = new javax.swing.JLabel();
        cbhang = new javax.swing.JLabel();
        tfhang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbma = new javax.swing.JLabel();
        tfma = new javax.swing.JTextField();
        tften = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tathongtin = new javax.swing.JTextArea();
        cbmodel = new javax.swing.JLabel();
        tfmodel = new javax.swing.JTextField();
        tfmau = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbmau = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfsl = new javax.swing.JTextField();
        cbsl = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bnhapkho = new javax.swing.JButton();
        bhuybo = new javax.swing.JButton();
        bg = new javax.swing.ButtonGroup();
        psuadoi = new java.awt.Panel();
        jLabel7 = new javax.swing.JLabel();
        tftimhang = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        thongbaothanhcong = new javax.swing.JOptionPane();
        dketnoi = new javax.swing.JDialog(fkhohang,true);
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        fkhohang.setMinimumSize(new java.awt.Dimension(800, 600));
        fkhohang.setResizable(false);

        pmenu.setPreferredSize(new java.awt.Dimension(250, 650));
        pmenu.setRequestFocusEnabled(false);
        pmenu.setLayout(new java.awt.BorderLayout());

        pmenunorth.setPreferredSize(new java.awt.Dimension(200, 180));

        lquyenacc.setForeground(new java.awt.Color(0, 0, 255));
        lquyenacc.setText("Bạn đang đăng nhập với quyền kho hàng");

        lhi.setFont(new java.awt.Font("Times New Roman", 1, 12));
        lhi.setForeground(new java.awt.Color(255, 0, 51));
        lhi.setText("Xin chào");

        l1.setText("Bạn có quyền quản lý");

        l3.setText("1> Nhập mặt hàng mới vào kho.");

        l4.setText("2> Quản lý hàng trong kho.");

        jProgressBar1.setBackground(new java.awt.Color(204, 204, 204));

        lacc.setFont(new java.awt.Font("Times New Roman", 1, 14));
        lacc.setForeground(new java.awt.Color(255, 0, 153));
        lacc.setText(new hamgoi().docusername());

        javax.swing.GroupLayout pmenunorthLayout = new javax.swing.GroupLayout(pmenunorth);
        pmenunorth.setLayout(pmenunorthLayout);
        pmenunorthLayout.setHorizontalGroup(
            pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmenunorthLayout.createSequentialGroup()
                .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pmenunorthLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(l1)
                        .addGap(83, 83, 83))
                    .addGroup(pmenunorthLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l3)
                            .addComponent(l4))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmenunorthLayout.createSequentialGroup()
                        .addContainerGap(42, Short.MAX_VALUE)
                        .addComponent(lhi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lacc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(pmenunorthLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lquyenacc, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pmenunorthLayout.setVerticalGroup(
            pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmenunorthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pmenunorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lhi)
                    .addComponent(lacc, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lquyenacc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1)
                .addGap(18, 18, 18)
                .addComponent(l3)
                .addGap(11, 11, 11)
                .addComponent(l4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pmenu.add(pmenunorth, java.awt.BorderLayout.NORTH);

        pmenucenter.setPreferredSize(new java.awt.Dimension(200, 400));
        pmenucenter.setLayout(new java.awt.BorderLayout());

        pbcenter1.setPreferredSize(new java.awt.Dimension(200, 250));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Nhập thêm một mặt hàng mới");

        bnhap.setText("Nhập");
        bnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnhapActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Quản lý hàng hóa trong kho");

        bquanly.setText("Danh sách");
        bquanly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquanlyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pbcenter1Layout = new javax.swing.GroupLayout(pbcenter1);
        pbcenter1.setLayout(pbcenter1Layout);
        pbcenter1Layout.setHorizontalGroup(
            pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbcenter1Layout.createSequentialGroup()
                .addGroup(pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(bnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(pbcenter1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(bquanly, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pbcenter1Layout.setVerticalGroup(
            pbcenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbcenter1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bnhap)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(bquanly)
                .addGap(87, 87, 87))
        );

        pmenucenter.add(pbcenter1, java.awt.BorderLayout.NORTH);

        pmenu.add(pmenucenter, java.awt.BorderLayout.CENTER);

        pmenusouth.setLayout(new java.awt.BorderLayout());

        pmenusouth1.setPreferredSize(new java.awt.Dimension(200, 100));

        bexit.setText("Exit");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        jProgressBar2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pmenusouth1Layout = new javax.swing.GroupLayout(pmenusouth1);
        pmenusouth1.setLayout(pmenusouth1Layout);
        pmenusouth1Layout.setHorizontalGroup(
            pmenusouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmenusouth1Layout.createSequentialGroup()
                .addGroup(pmenusouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pmenusouth1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pmenusouth1Layout.setVerticalGroup(
            pmenusouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmenusouth1Layout.createSequentialGroup()
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bexit)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pmenusouth.add(pmenusouth1, java.awt.BorderLayout.SOUTH);

        pmenu.add(pmenusouth, java.awt.BorderLayout.PAGE_END);

        fkhohang.getContentPane().add(pmenu, java.awt.BorderLayout.WEST);

        pchinh.setMinimumSize(new java.awt.Dimension(600, 600));
        pchinh.setPreferredSize(new java.awt.Dimension(620, 650));

        pcenter.setMinimumSize(new java.awt.Dimension(590, 600));
        pcenter.setPreferredSize(new java.awt.Dimension(600, 650));
        pcenter.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pchinhLayout = new javax.swing.GroupLayout(pchinh);
        pchinh.setLayout(pchinhLayout);
        pchinhLayout.setHorizontalGroup(
            pchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pchinhLayout.createSequentialGroup()
                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pcenter, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
        );
        pchinhLayout.setVerticalGroup(
            pchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pchinhLayout.createSequentialGroup()
                .addGroup(pchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fkhohang.getContentPane().add(pchinh, java.awt.BorderLayout.CENTER);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Mã hàng");

        cbten.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbten.setForeground(new java.awt.Color(255, 0, 0));
        cbten.setText(" ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Tên hàng");

        cbgianhap.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbgianhap.setForeground(new java.awt.Color(255, 0, 0));
        cbgianhap.setText(" ");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 2, 12));
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText(" ");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("Giá bán ra");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("Nhâp thông tin hàng cần thêm vào kho");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel27.setForeground(new java.awt.Color(0, 0, 255));
        jLabel27.setText("Thông tin chi tiết về sản phẩm");

        cbgiaban.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbgiaban.setForeground(new java.awt.Color(255, 0, 0));
        cbgiaban.setText(" ");

        cbhang.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbhang.setForeground(new java.awt.Color(255, 0, 0));
        cbhang.setText(" ");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Hãng sản xuất");

        cbma.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbma.setForeground(new java.awt.Color(255, 0, 0));
        cbma.setText(" ");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Model");

        tathongtin.setColumns(20);
        tathongtin.setRows(5);
        jScrollPane1.setViewportView(tathongtin);

        cbmodel.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbmodel.setForeground(new java.awt.Color(255, 0, 0));
        cbmodel.setText(" ");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("Màu sắc");

        cbmau.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbmau.setForeground(new java.awt.Color(255, 0, 0));
        cbmau.setText(" ");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("Số lượng");

        cbsl.setFont(new java.awt.Font("Times New Roman", 2, 12));
        cbsl.setForeground(new java.awt.Color(255, 0, 0));
        cbsl.setText(" ");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("Giá nhập vào");

        bnhapkho.setText("Nhập kho");
        bnhapkho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnhapkhoActionPerformed(evt);
            }
        });

        bhuybo.setText("Hủy bỏ");
        bhuybo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhuyboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnhapkhoLayout = new javax.swing.GroupLayout(pnhapkho);
        pnhapkho.setLayout(pnhapkhoLayout);
        pnhapkhoLayout.setHorizontalGroup(
            pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnhapkhoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnhapkhoLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(38, 38, 38))
                    .addGroup(pnhapkhoLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(bnhapkho)
                        .addGap(28, 28, 28)
                        .addComponent(bhuybo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(pnhapkhoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27)
                    .addComponent(jScrollPane1)
                    .addGroup(pnhapkhoLayout.createSequentialGroup()
                        .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18)
                            .addComponent(jLabel22))
                        .addGap(13, 13, 13)
                        .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfsl)
                            .addComponent(tfma)
                            .addComponent(cbten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tften, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(tfhang)
                            .addComponent(tfmodel)
                            .addComponent(tfmau)
                            .addComponent(tfgianhap)
                            .addComponent(cbhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnhapkhoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(cbma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cbmodel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbmau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbsl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbgianhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnhapkhoLayout.createSequentialGroup()
                                .addComponent(cbgiaban, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addComponent(tfgiaban, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        pnhapkhoLayout.setVerticalGroup(
            pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnhapkhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(30, 30, 30)
                .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tften, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbten)
                .addGap(5, 5, 5)
                .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbma)
                .addGap(5, 5, 5)
                .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbhang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmodel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfmau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbsl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tfgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbgianhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cbgiaban))
                .addGap(52, 52, 52)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnhapkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bhuybo)
                    .addComponent(bnhapkho))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 0, 255));
        jLabel7.setText("Tim kiếm mặt hàng");

        jButton4.setText("Tìm kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel28.setForeground(new java.awt.Color(255, 0, 51));
        jLabel28.setText("Danh sách các mặt hàng tìm được");

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên hàng", "Mã hàng", "Hãng sản xuất", "Model", "Màu sắc", "Số lượng", "Giá nhập vào", "Giá bán ra", "Thông tin", "Ngày nhập"
            }
        ));
        jScrollPane3.setViewportView(tb2);

        jButton5.setText("Sửa đổi");

        jButton6.setText("Xóa");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Tìm kiếm theo mã hàng hoặc tên hang");

        javax.swing.GroupLayout psuadoiLayout = new javax.swing.GroupLayout(psuadoi);
        psuadoi.setLayout(psuadoiLayout);
        psuadoiLayout.setHorizontalGroup(
            psuadoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psuadoiLayout.createSequentialGroup()
                .addGroup(psuadoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(psuadoiLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel7))
                    .addGroup(psuadoiLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel28)))
                .addContainerGap(234, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
            .addGroup(psuadoiLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(psuadoiLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(psuadoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(psuadoiLayout.createSequentialGroup()
                        .addComponent(tftimhang, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        psuadoiLayout.setVerticalGroup(
            psuadoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psuadoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(psuadoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftimhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(23, 23, 23)
                .addComponent(jLabel28)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(psuadoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        dketnoi.setTitle("Lỗi kết nối");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Không thể kết nối tới Server");

        jButton8.setText("OK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dketnoiLayout = new javax.swing.GroupLayout(dketnoi.getContentPane());
        dketnoi.getContentPane().setLayout(dketnoiLayout);
        dketnoiLayout.setHorizontalGroup(
            dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dketnoiLayout.createSequentialGroup()
                .addGroup(dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dketnoiLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10))
                    .addGroup(dketnoiLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        dketnoiLayout.setVerticalGroup(
            dketnoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dketnoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnhapActionPerformed
        tften.setText("");
        tfma.setText("");
        tfhang.setText("");
        tfmodel.setText("");
        tfmau.setText("");
        tfsl.setText("");
        tfgianhap.setText("");
        tfgiaban.setText("");
        tathongtin.setText("");
        cbten.setText("");
        cbma.setText("");
        cbhang.setText("");
        cbmodel.setText("");
        cbmau.setText("");
        cbsl.setText("");
        cbgianhap.setText("");
        cbgiaban.setText("");
        pcenter.removeAll();
        fkhohang.pack();
        pcenter.add(pnhapkho,java.awt.BorderLayout.CENTER);
        fkhohang.pack();
}//GEN-LAST:event_bnhapActionPerformed

    private void bquanlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquanlyActionPerformed
        pcenter.removeAll();
        fkhohang.pack();
        pcenter.add(psuadoi,java.awt.BorderLayout.WEST);
        fkhohang.pack();
}//GEN-LAST:event_bquanlyActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        System.exit(1);
}//GEN-LAST:event_bexitActionPerformed

    private void bhuyboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhuyboActionPerformed
        pcenter.removeAll();
        fkhohang.pack();
    }//GEN-LAST:event_bhuyboActionPerformed

    private void bnhapkhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnhapkhoActionPerformed
        cbten.setText("");
        cbma.setText("");
        cbhang.setText("");
        cbmodel.setText("");
        cbmau.setText("");
        cbsl.setText("");
        cbgianhap.setText("");
        cbgiaban.setText("");
        boolean check=true;
        if(new hamgoi().ktString(tften.getText())==false){
            cbten.setText("* Bat buoc phai nhap du lieu nay!");
            check=false;
        }
        if(new hamgoi().ktString(tfma.getText())==false){
            cbma.setText("* Bat buoc phai nhap du lieu nay!");
            check=false;
        }
        if(new hamgoi().ktString(tfhang.getText())==false){
            cbhang.setText("* Bat buoc phai nhap du lieu nay!");
            check=false;
        }
        if(new hamgoi().ktString(tfmodel.getText())==false){
            cbmodel.setText("* Bat buoc phai nhap du lieu nay!");
            check=false;
        }
        if(new hamgoi().ktString(tfmau.getText())==false){
            cbmau.setText("* Bat buoc phai nhap du lieu nay!");
            check=false;
        }
        if(new hamgoi().ktLong(tfsl.getText())==false){
            cbsl.setText("* Du lieu kieu so! VD 300.");
            check=false;
        }
        if(new hamgoi().ktLong(tfgianhap.getText())==false){
            cbgianhap.setText("* Du lieu kieu so! VD 300.");
            check=false;
        }
        if(new hamgoi().ktLong(tfgiaban.getText())==false){
            cbgiaban.setText("* Du lieu kieu so! VD 300.");
            check=false;
        }
        if(check==true){
            try{
                Serverconnection1 = (Control.RemoteServer)Naming.lookup("rmi://"+ip+":1099/Server");
                s2=Serverconnection1.data("nhaphang",tften.getText(),tfma.getText(),tfhang.getText(),tfmodel.getText(),tfmau.getText(),tfsl.getText(),tfgianhap.getText(),tfgiaban.getText(),tathongtin.getText(),"");
                if(s2[0].equals("trungten")==true){
                    cbten.setText("* Tên hàng này đã có trong kho!");
                }
                if(s2[0].equals("trungma")==true){
                    cbma.setText("* Mã hàng này đã được sử dụng");
                }
                else if(s2[0].equals("thanhcong")==true){
                    javax.swing.JOptionPane.showMessageDialog(thongbaothanhcong, "Thông tin loại hàng mới đã được đưa vào kho.");
                    pcenter.removeAll();
                    fkhohang.pack();
                }
            }
            catch(Exception e){
                dketnoi.pack();
                dketnoi.setVisible(true);
            }
        }
    }//GEN-LAST:event_bnhapkhoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model=(DefaultTableModel)tb2.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            Serverconnection1 = (Control.RemoteServer)Naming.lookup("rmi://"+ip+":1099/Server");
            s2=Serverconnection1.data("timhang",tftimhang.getText(),"","","","","","","","","");
            if(s2[0].equals("timthay")==true){
                model.addRow(new Object[] {s2[1],s2[2],s2[3],s2[4],s2[5],s2[6],s2[7],s2[8],s2[9],s2[10]});
            }
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dketnoi.setVisible(false);
}//GEN-LAST:event_jButton8ActionPerformed
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               //new Login().abc();

                new fnhapkho().fkhohang.pack();
                new fnhapkho().fkhohang.setVisible(true);
            }
        });
    }
    /**
    * @param args the command line arguments
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexit;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton bhuybo;
    private javax.swing.JButton bnhap;
    private javax.swing.JButton bnhapkho;
    private javax.swing.JButton bquanly;
    private javax.swing.JLabel cbgiaban;
    private javax.swing.JLabel cbgianhap;
    private javax.swing.JLabel cbhang;
    private javax.swing.JLabel cbma;
    private javax.swing.JLabel cbmau;
    private javax.swing.JLabel cbmodel;
    private javax.swing.JLabel cbsl;
    private javax.swing.JLabel cbten;
    private javax.swing.JDialog dketnoi;
    public javax.swing.JFrame fkhohang;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel lacc;
    private javax.swing.JLabel lhi;
    private javax.swing.JLabel lquyenacc;
    private javax.swing.JPanel pbcenter1;
    private javax.swing.JPanel pcenter;
    private javax.swing.JPanel pchinh;
    private javax.swing.JPanel pmenu;
    private javax.swing.JPanel pmenucenter;
    private javax.swing.JPanel pmenunorth;
    private javax.swing.JPanel pmenusouth;
    private javax.swing.JPanel pmenusouth1;
    private java.awt.Panel pnhapkho;
    private java.awt.Panel psuadoi;
    private javax.swing.JTextArea tathongtin;
    private javax.swing.JTable tb2;
    private javax.swing.JTextField tfgiaban;
    private javax.swing.JTextField tfgianhap;
    private javax.swing.JTextField tfhang;
    private javax.swing.JTextField tfma;
    private javax.swing.JTextField tfmau;
    private javax.swing.JTextField tfmodel;
    private javax.swing.JTextField tfsl;
    private javax.swing.JTextField tften;
    private javax.swing.JTextField tftimhang;
    private javax.swing.JOptionPane thongbaothanhcong;
    // End of variables declaration//GEN-END:variables

}
